# executes all code cells (=examples) in the notebooks

name: examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  run_notebooks:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: sudo apt-get install libportaudio2
      - run: pip install -r requirements.txt
      - uses: treebeardtech/treebeard@master
        with:
          use-docker: false
